services:

  postgres:
    image: postgres:16
    container_name: payment-postgres

    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
      POSTGRES_DB: payment_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  streamlit:
    build:
      context: ./dashboard
    container_name: payment-dashboard

    ports:
      - "8501:8501"

    depends_on:
      - postgres

volumes:
  postgres_data: